apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: wardle
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  #selector:
  #  apiserver: "true"
  type: ExternalName
  externalName: localhost
